### ISSUE TITLE
InternalError (see above for traceback): Blas SGEMM launch failed

### ISSUE THREAD

**Issue by vincenttsai2015** [vijayvee/Recursive-neural-networks-TensorFlow#1]
I cloned and executed this code in my server with a single GPU, but the error message is shown as follows:

E tensorflow/stream_executor/cuda/cuda_blas.cc:372] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
W tensorflow/stream_executor/stream.cc:1390] attempting to perform BLAS operation using StreamExecutor without BLAS support
E tensorflow/stream_executor/cuda/cuda_blas.cc:372] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
W tensorflow/stream_executor/stream.cc:1390] attempting to perform BLAS operation using StreamExecutor without BLAS support
Traceback (most recent call last):
  File "rnn.py", line 340, in <module>
    test_RNN()
  File "rnn.py", line 322, in test_RNN
    stats = model.train(verbose=True)
  File "rnn.py", line 270, in train
    train_acc, val_acc, loss_history, val_loss = self.run_epoch(new_model=True)
  File "rnn.py", line 234, in run_epoch
    loss, _ = sess.run([loss, train_op])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 766, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 964, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1014, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1034, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Blas SGEMM launch failed : a.shape=(1, 70), b.shape=(70, 35), m=1, n=35, k=70
         [[Node: MatMul = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false, _device="/job:localhost/replica:0/task:0/gpu:0"](concat, Composition/W1/read)]]
         [[Node: add_6/_17 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_299_add_6", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Caused by op u'MatMul', defined at:
  File "rnn.py", line 340, in <module>
    test_RNN()
  File "rnn.py", line 322, in test_RNN
    stats = model.train(verbose=True)
  File "rnn.py", line 270, in train
    train_acc, val_acc, loss_history, val_loss = self.run_epoch(new_model=True)
  File "rnn.py", line 230, in run_epoch
    logits = self.inference(tree)
  File "rnn.py", line 50, in inference
    node_tensors = self.add_model(tree.root)
  File "rnn.py", line 107, in add_model
    node_tensors.update(self.add_model(node.left))
  File "rnn.py", line 107, in add_model
    node_tensors.update(self.add_model(node.left))
  File "rnn.py", line 108, in add_model
    node_tensors.update(self.add_model(node.right))
  File "rnn.py", line 111, in add_model
    curr_node_tensor=tf.nn.relu(tf.matmul(child_tensor,W1) + b1)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/math_ops.py", line 1729, in matmul
    a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 1442, in _mat_mul
    transpose_b=transpose_b, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 759, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2240, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1128, in __init__
    self._traceback = _extract_stack()

InternalError (see above for traceback): Blas SGEMM launch failed : a.shape=(1, 70), b.shape=(70, 35), m=1, n=35, k=70
         [[Node: MatMul = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false, _device="/job:localhost/replica:0/task:0/gpu:0"](concat, Composition/W1/read)]]
         [[Node: add_6/_17 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_299_add_6", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

My GPU information:
![image](https://cloud.githubusercontent.com/assets/13366052/22184009/0a9ac40e-e105-11e6-9d97-0140c9bf2a4d.png)

This code works fine with CPU server, but I can't figure out what's wrong with my GPU server......

Is there any suggestion? Thanks.

**Comment by vincenttsai2015** [comment]
I just settled this by setting the configuration in the sessions of the functions "predict" and "run_epoch" as follows:

config = tf.ConfigProto()
config.gpu_options.allow_growth = True
tf.Session(config=config)
